POST http://trial.orca.med.or.jp:8000/api01rv2/acceptlstv2?class=03 HTTP/1.1
Content-Type: application/xml
Authorization: Basic trial:

<data>
  <acceptlstreq type="record">
    <Acceptance_Date type="string">2020-10-01</Acceptance_Date>
  </acceptlstreq>
</data>

###

POST http://trial.orca.med.or.jp:8000/api01rv2/medicalgetv2?class=01
Content-Type: application/xml
Authorization: Basic trial: 

<data>
        <medicalgetreq type="record">
                <Patient_ID type="string">3</Patient_ID>
                <Perform_Date type="string">2020-10-01</Perform_Date>
        </medicalgetreq>
</data>


###

POST http://trial.orca.med.or.jp:8000/api01rv2/visitptlstv2
Content-Type: application/xml
Authorization: Basic trial: 

<data>
    <visitptlstreq type="record">
        <Request_Number type="string">01</Request_Number>
        <Visit_Date type="string">2020-10-01</Visit_Date>
　　</visitptlstreq>
</data>

###

POST http://trial.orca.med.or.jp:8000/api01rv2/tmedicalgetv2
Content-Type: application/xml
Authorization: Basic trial: 

<data>
        <tmedicalgetreq type="record">
                <Perform_Date type="string">2020-10-01</Perform_Date>
                <Patient_ID type="string"></Patient_ID>
        </tmedicalgetreq>
</data>

###

GET http://trial.orca.med.or.jp:8000/api01rv2/patientgetv2?id=3
Content-Type: application/xml
Authorization: Basic trial: 
