"""a

Revision ID: af45055da2f0
Revises: 
Create Date: 2020-09-17 14:13:41.189882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af45055da2f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceptances',
    sa.Column('Acceptance_ID', sa.String(length=256), nullable=False),
    sa.Column('Acceptance_Date', sa.String(length=256), nullable=False),
    sa.Column('Acceptance_Time', sa.String(length=256), nullable=False),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('Patient_ID', sa.String(length=256), nullable=True),
    sa.Column('InsuranceProvider_WholeName', sa.String(length=256), nullable=True),
    sa.Column('Department_WholeName', sa.String(length=256), nullable=True),
    sa.Column('Physician_WholeName', sa.String(length=256), nullable=True),
    sa.Column('Patient_Memo', sa.String(length=256), nullable=True),
    sa.Column('Acceptance_Memo', sa.String(length=256), nullable=True),
    sa.Column('BigData', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Acceptance_ID', 'Acceptance_Date')
    )
    op.create_index(op.f('ix_acceptances_Acceptance_Time'), 'acceptances', ['Acceptance_Time'], unique=False)
    op.create_index(op.f('ix_acceptances_Status'), 'acceptances', ['Status'], unique=False)
    op.create_table('patients',
    sa.Column('Patient_ID', sa.String(length=256), nullable=False),
    sa.Column('WholeName', sa.String(length=256), nullable=True),
    sa.Column('WholeName_inKana', sa.String(length=256), nullable=True),
    sa.Column('BirthDate', sa.String(length=256), nullable=True),
    sa.Column('Sex', sa.String(length=256), nullable=True),
    sa.Column('LastVisit_Date', sa.String(length=256), nullable=True),
    sa.Column('Patient_Memo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('Patient_ID')
    )
    op.create_index(op.f('ix_patients_WholeName'), 'patients', ['WholeName'], unique=False)
    op.create_index(op.f('ix_patients_WholeName_inKana'), 'patients', ['WholeName_inKana'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_WholeName_inKana'), table_name='patients')
    op.drop_index(op.f('ix_patients_WholeName'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_acceptances_Status'), table_name='acceptances')
    op.drop_index(op.f('ix_acceptances_Acceptance_Time'), table_name='acceptances')
    op.drop_table('acceptances')
    # ### end Alembic commands ###
